# Generated by Django 3.2.3 on 2021-05-23 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='ユーザ名')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id_building', models.AutoField(primary_key=True, serialize=False, verbose_name='建物ID')),
                ('name_building', models.CharField(max_length=255, verbose_name='建物名')),
                ('address_lat', models.DecimalField(decimal_places=7, default=0, max_digits=10, verbose_name='緯度')),
                ('address_lon', models.DecimalField(decimal_places=7, default=0, max_digits=10, verbose_name='経度')),
                ('risk_rate', models.IntegerField(blank=True, default=-1, null=True, verbose_name='危険度')),
                ('own_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理者')),
            ],
        ),
        migrations.CreateModel(
            name='VibrationData',
            fields=[
                ('id_vibration_data', models.AutoField(primary_key=True, serialize=False, verbose_name='揺れデータ')),
                ('vibration_data', models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%d')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.building')),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frequency', models.FloatField(blank=True, default=-1, null=True, verbose_name='FFT結果')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vibrationdata')),
            ],
        ),
    ]
